/**
 * Fichier data.js - Source unique de vérité pour tous les produits.
 * Ajout du champ 'galleryImages' pour la capacité 3.
 */

const ALL_PRODUCTS = [
    { 
        id: 1, 
        title: "Gachiakuta", 
        genre: "action", 
        mediaType: "manga", 
        price: 300, 
        date: "2022-02-01", 
        minVolume: 1, // NOUVEAU
        maxVolume: 10, // NOUVEAU
        author: "Kei Urana",
        pages: 20,
        format: "CBR, PDF",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BZDU5ZmEzODYtMDU2OS00NTZiLTk4MWYtYWUyZWUzNGU2ODdjXkEyXkFqcGc@._V1_.jpg",
        summary: "Rudo, un jeune homme rejeté par la société et envoyé dans un immense dépotoir où survivre est presque impossible. Dans ce monde brutal rempli de déchets, de créatures étranges et de secrets enfouis, Rudo découvre qu’il possède un pouvoir lié à des objets jetés par les humains. Guidé par de nouveaux alliés, il cherche à comprendre la vérité sur ce système injuste et sur son propre passé.",
        rating: "★★★★☆",
        // NOUVEAU: Images pour la galerie de détails
        galleryImages: [
            "https://via.placeholder.com/600x900/00FFFF/FF4136?text=Manga+T1+(Couverture)",
            "https://via.placeholder.com/600x900/4169E1/FFFFFF?text=Manga+T1+(Page+Int.)",
            "https://via.placeholder.com/600x900/FFDC00/333333?text=Manga+T1+(Dos)",
            "https://via.placeholder.com/600x900/7CFC00/333333?text=Manga+T1+(Bonus)"
        ]
    },
    { 
        id: 2, 
        title: "Sexy Cosplay Doll", 
        genre: "fantasy", 
        mediaType: "manga", 
        price: 800, 
        date: "2019-10-25", 
        minVolume: 1, maxVolume: 2,
        author: "Shin'ichi Fukuda",
        pages: 202,
        format: "CBZ, PDF",
        imageUrl: "https://m.media-amazon.com/images/I/815lmrIk-fL._AC_UF1000,1000_QL80_.jpg",
        summary: "Wakana Gojo est un lycéen de première année qui rêve de devenir un artisan de poupées hina, à l'instar de son grand-père. Un jour, au cours de son premier semestre, sa camarade de classe Marine Kitagawa, très populaire dans le lycée, le surprend en train de réaliser des costumes de poupées dans la salle de confection de vêtements de l'école.",
        rating: "★★★★★",
        galleryImages: [
            "https://via.placeholder.com/600x900/FF4136/00FFFF?text=Comic+S.F.",
            "https://via.placeholder.com/600x900/8B008B/FFFFFF?text=Comic+S.F.+(Scene+1)",
            "https://via.placeholder.com/600x900/000000/FF4136?text=Comic+S.F.+(Page+Fin)",
        ]
    },
    { 
        id: 3, 
        title: "Marvel's Thor : Ragnarok", 
        genre: "action", 
        mediaType: "comics", 
        price: 1300, 
        date: "2017-06-23", 
        minVolume: 1, maxVolume: 1,
        author: "Olivier Coipel",
        pages: 152,
        format: "Webtoon, PDF",
        imageUrl: "https://cdn.marvel.com/u/prod/marvel/i/mg/d/20/59cba89d5fd54/portrait_uncanny.jpg",
        summary: "Le cycle éternel de Ragnarok décrit la naissance, la mort et la résurrection des dieux Asgardiens. Un cycle auquel Thor veut mettre fin. C’est une décision lourde de conséquences, puisqu’elle pourrait signer la disparition du panthéon d’Asgard.",
        rating: "★★★☆☆",
        galleryImages: [
            "https://via.placeholder.com/600x900/333333/FFFFFF?text=Scan+Horreur",
            "https://via.placeholder.com/600x900/800000/FFFFFF?text=Scan+Horreur+(Aperçu)"
        ]},
    { id: 4, title: "Sky-High Survival", genre: "fantasy", mediaType: "manga", price: 500, date: "2013-04-15", minVolume: 1, maxVolume: 5, author: "Oba Takahiro", pages: 192, format: "CBR, PDF", imageUrl: "https://bdi.dlpdomain.com/album/9782505067498-couv-M300x425.jpg", detailImageUrl: "https://www.planetebd.com/dynamicImages/album/page/large/32/53/album-page-large-32536.jpg", summary: "Yuri Honjo est une lycéenne qui se retrouve soudainement sur le toit d'un immeuble, dans un monde étrange entouré de gratte-ciels. Elle tombe nez à nez avec un homme masqué qui a fendu la tête d'un homme en deux. Les gratte-ciels sont reliés par des ponts et Yuri tente de retrouver son frère qui se trouve dans le même monde qu'elle. Mais existe t-il une sortie autre que de sauter d'un toit ?", rating: "★★★★☆", galleryImages: ["https://www.planetebd.com/dynamicImages/album/page/large/33/98/album-page-large-33985.jpg"] },
    { id: 5, title: "GE-Good Ending", genre: "fantasy", mediaType: "manga", price: 500, date: "2009-11-20", minVolume: 1, maxVolume: 16, author: "sasuga kei", pages: 192, format: "CBZ", imageUrl: "https://www.nautiljon.com/images/manga/00/47/ge_-_good_ending_2274.webp", detailImageUrl: "https://m.media-amazon.com/images/I/81yxlrjlOrL._AC_UF1000,1000_QL80_.jpg", summary: "Seiji Utsumi est un adolescent comme tant d'autre. Maladroit en amour, il est tétanisé rien qu'à l'idée d'avouer ses sentiments à celle qu'il aime : Shô Iketani.", rating: "★★★★☆", galleryImages: ["https://m.media-amazon.com/images/I/81dPu7GzfDL._AC_UF1000,1000_QL80_.jpg"] },
    { id: 6, title: "Takane No Hana", genre: "fantasy", mediaType: "manga", price: 500, date: "2024-05-01", minVolume: 1, maxVolume: 5, author: "Yuki Shiwazu", pages: 192, format: "Webtoon", imageUrl: "https://www.manga-news.com/public/images/series/takane-hana-1-kaze.webp", detailImageUrl: "https://www.bedetheque.com/media/Planches/PlancheS_53073.jpg", summary: "Hana, lycéenne de 16 ans, est contrainte de prendre la place de sa sœur lors d’une rencontre arrangée ! Présentée à l'héritier du grand groupe Takaba, le très séduisant Takane Saibara, la jeune fille déchante vite face à son arrogance.", rating: "★★★★☆", galleryImages: ["https://www.sanctuary.fr/public/img/objet/origin/253630-8.jpg"] },
    { id: 7, title: "Domestic Girlfriend", genre: "fantasy", mediaType: "manga", price: 500, date: "2016-09-10", minVolume: 1, maxVolume: 5, author: "Sasuga Kei", pages: 192, format: "CBR", imageUrl: "https://www.manga-news.com/public/images/vols/Love_X_Dilemma_T28_-__dition_sp_ciale_-_Delcourt_Tonkam.webp", detailImageUrl: "https://www.sanctuary.fr/public/img/objet/origin/247608-9.jpg", summary: "Shuichi Kagaya est un jeune étudiant qui a la singularité de pouvoir se transformer en monstre, chose qu'il essaye de cacher à tout prix. Cependant, après avoir sauvé une jeune fille, Claire Aoki, elle découvre son secret. Cette dernière va alors faire équipe avec Shuichi pour retrouver sa sœur qui a tué sa famille...", rating: "★★★★☆", galleryImages: ["https://www.planetebd.com/dynamicImages/album/page/large/35/78/album-page-large-35784.jpg"] },
    { id: 8, title: "Gleipnir", genre: "promos", mediaType: "manga", price: 500, date: "2018-02-28", minVolume: 1, maxVolume: 5, author: "Takeda Sun", pages: 176, format: "CBZ", imageUrl: "https://www.nautiljon.com/images/manga/00/55/gleipnir_5855.webp", detailImageUrl: "https://www.bdweb.fr/images/photolib/370x520c/543198/543198.jpg", summary: "Shuichi Kagaya est un jeune étudiant qui a la singularité de pouvoir se transformer en monstre, chose qu'il essaye de cacher à tout prix. Cependant, après avoir sauvé une jeune fille, Claire Aoki, elle découvre son secret. Cette dernière va alors faire équipe avec Shuichi pour retrouver sa sœur qui a tué sa famille...", rating: "★★★★☆", galleryImages: ["https://www.bdweb.fr/images/photolib/noresize/543200/543200.jpg"] },
    { id: 9, title: "Immortal Hulk", genre: "action", mediaType: "comics", price: 1000, date: "201-08-10", minVolume: 1, maxVolume: 10, author: "Ewing", pages: 128, format: "CBZ, CBR", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_361867.jpg", detailImageUrl: "https://preview.redd.it/immortal-hulk-2018-v0-8037gq41tyoc1.png?auto=webp&s=e8748de5c7b4263bf79dc559439eaef09c70af98", summary: " Chaque fois que Bruce Banner meurt, Hulk revient à la vie quelques heures plus tard. À la nuit tombée, le Colosse de Jade devient cruel et déterminé. Découvrez Hulk comme vous ne l'avez jamais vu... Ce récit glaçant s'est imposé immédiatement comme une version culte du personnage.", rating: "★★★★☆", galleryImages: ["https://static.fnac-static.com/multimedia/PE/Images/FR/NR/f6/d2/14/18141942/1520-1/tsp20250314084207/Immortal-Hulk-T01.jpg"] },
    { id: 10, title: "Batman Dark Patterns", genre: "aventure", mediaType: "comics", price: 1200, date: "2025-05-10", minVolume: 1, maxVolume: 1, author: "Dan Watters", pages: 80, format: "CBZ, CBR", imageUrl: "https://bdi.dlpdomain.com/album/9791026825524/couv/M385x862/batman-dark-patterns-affaire-1-l-rsquo-homme-blesse.jpg", detailImageUrl: "https://www.bedetheque.com/media/Planches/PlancheA_521960.jpg", summary: "Une série de meurtres effroyables a provoqué une onde de choc à Gotham. La piste mène tout droit vers un sinistre tueur en série, au corps percé d'innombrables clous et baptisé l'écorché. Mais s'agit-il des agissements d'un seul désaxé, ou y a-t-il quelque chose d'encore plus sinistre en jeu ?", rating: "★★★★☆", galleryImages: ["https://www.comicsblog.fr/images/editeur/AdminCorentin/News/PXT-29/batman-dark-patterns-2.jpg"] },
    { id: 11, title: "Joker Infinite", genre: "action", mediaType: "comics", price: 1300, date: "2024-08-19", minVolume: 1, maxVolume: 3, author: "James Tynion IV", pages: 160, format: "CBZ, CBR", imageUrl: "https://bdi.dlpdomain.com/album/9791026828211/couv/M385x862/joker-infinite-integrale.jpg", detailImageUrl: "https://www.bedetheque.com/media/Planches/PlancheS_78516.jpg", summary: "Depuis les événements qui paralysèrent sa fille Barbara, l'ex-commissaire reste hanté par la barbarie du Joker. Aussi, lorsque la représentante d'une mystérieuse organisation lui propose d'assassiner le Joker, Gordon y voit l'occasion de faire ce que Batman ne se résoudra jamais à faire et de débarrasser une bonne fois pour toute le monde de cet avatar du Mal absolu.", rating: "★★★★☆", galleryImages: ["https://www.bedetheque.com/media/Planches/PlancheA_444667.jpg"] },
    { id: 12, title: "Batman - Joker War", genre: "action", mediaType: "comics", price: 1300, date: "2020-09-18", minVolume: 1, maxVolume: 3, author: "Guillem March", pages: 272, format: "CBZ, CBR", imageUrl: "https://bdi.dlpdomain.com/album/9791026817123/couv/M385x862/batman-joker-war-tome-1.jpg", detailImageUrl: "https://static.pulps.fr/img/APR20/full/STL157521.jpg", summary: "À présent que la ville de Gotham est libérée du joug de Bane, Batman et Catwoman ont décidé de s'associer pour rendre la justice dans la ville déchue. Mais une affaire ancienne qui a impliqué la féline cambrioleuse et les plus grands ennemis du Chevalier Noir menace de refaire surface quand le Designer, un super-vilain oublié, fait sa réapparition. ", rating: "★★★★☆", galleryImages: ["https://cdn.mos.cms.futurecdn.net/PYzevaJ4wsmzDQAi4s2QAL.jpg"] },
    { id: 13, title: "Ultimates Hors Série - Ultimate Iron Man", genre: "action", mediaType: "comics", price: 1000, date: "2008-10-01", minVolume: 5, maxVolume:6, author: "Orson Scott Card", pages: 107, format: "CBZ, CBR", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_79370.jpg", detailImageUrl: "https://www.bedetheque.com/media/Planches/PlancheA_57151.jpg", summary: "Depuis toujours, Tony Stark est quelqu’un à part. Sa mère, la scientifique Maria Stark, lui transmet accidentellement un virus qui modifie son ADN. Dès lors, le corps de Tony est capable de se régénérer très rapidement. Mais dans le même temps, ses cellules deviennent hypersensibles, ce qui lui provoque de terribles douleurs. Le père de Tony, le brillant Howard Stark, patron de Stark Enterprises, finit par mettre au point une armure ultra fine qui lui colle à la peau et soulage ses souffrances. ", rating: "★★★★☆", galleryImages: ["https://www.bedetheque.com/media/Planches/PlancheA_79370.jpg"] },
    { id: 14, title: "Marvel : Avengers 2020", genre: "scifi", mediaType: "comics", price: 1000, date: "2020-01-01", minVolume: 1, maxVolume: 13, author: "Aaron, Jason", pages: 113, format: "CBR, CBZ", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_383213.jpg", detailImageUrl: "https://www.bedetheque.com/media/Planches/PlancheS_72704.jpg", summary: "Les Avengers sont de retour avec Captain America, Thor, Iron Man mais aussi Black Panther, Captain Marvel et Miss Hulk !", rating: "★★★★☆", galleryImages: ["https://www.bedetheque.com/media/Planches/PlancheA_366563.jpg"] },
    { id: 15, title: "Spider-Man : 6e série", genre: "scifi", mediaType: "comics", price: 700, date: "2017-06-19", minVolume: 1, maxVolume: 13, author: "Slott, Dan", pages: 96, format: "CBR, CBZ", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_309445.jpg", detailImageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_325321.jpg", summary: "Piqué par une araignée radioactive lors d'une expérience scientifique, peter parker acquiert d'extraordinaires pouvoirs, force et agilité surhumaines", rating: "★★★★☆", galleryImages: ["https://www.bedetheque.com/media/Couvertures/Couv_310607.jpg"] },
    { id: 16, title: "Deadpool : 4e série", genre: "scifi", mediaType: "comics", price: 600, date: "2016-06-01", minVolume: 1, maxVolume: 15, author: "Gerry Duggan", pages: 76, format: "CBR, CBZ", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_267196.jpg", detailImageUrl: "https://www.bedetheque.com/media/Planches/PlancheA_324212.jpg", summary: "Deadpool affronte ses plus grands adversaires : Thanos, Wolverine, Bullseye, T-Ray et le Docteur Bong. Le mercenaire va également vivre de bizarres ...", rating: "★★★★☆", galleryImages: ["https://www.bedetheque.com/media/Planches/PlancheA_358872.jpg"] },
    { id: 17, title: "Miles Morales : Spider-Man 2e série", genre: "nouveautes", mediaType: "comics", price: 1000, date: "2023-11-15", minVolume: 2, maxVolume: 3, author: "Ziglar, Cody", pages: 110, format: "CBR, CBZ", imageUrl: "https://www.excalibur-comics.fr/16669-large_default/spider-man-miles-morales-volume-2-omnibus.jpg", detailImageUrl: "https://preview.redd.it/do-you-prefer-miles-in-a-universe-where-peter-is-alive-or-v0-vzyihn9guu1d1.jpg?width=640&crop=smart&auto=webp&s=e7573f6df0443f0573b42239af6a6912b136024a", summary: "Miles Morales a survécu à bien des périls, et même à la mort de son univers d'origine ! Cette fois encore, une nouvelle ennemie débarque, et elle n'a en aucun cas l'intention d'épargner le jeune héros. ", rating: "★★★★☆", galleryImages: ["https://static.bdphile.fr/images/media/cover/0164/164263_1.jpg"] },
    { id: 18, title: "Docteur Fatalis", genre: "scifi", mediaType: "comics", price: 1000, date: "2019-06-11", minVolume: 1, maxVolume: 2, author: "Dan Slott", pages: 112, format: "CBR, CBZ", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_403164.jpg", detailImageUrl: "https://www.bedetheque.com/media/Versos/Verso_426916.jpg", summary: "Après les Quatre Fantastiques… le Docteur Fatalis est de retour ! Le seigneur de Latvérie s'oppose à une expérience scientifique qu'il juge trop dangereuse.", rating: "★★★★☆", galleryImages: ["https://www.bedetheque.com/media/Planches/PlancheA_426916.jpg"] },
    { id: 19, title: "Marvel : Fantastic Four 2019", genre: "scifi", mediaType: "comics", price: 1000, date: "2019-06-22", minVolume: 1, maxVolume: 6, author: "Dan Slott", pages: 100, format: "CBR, CBZ", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_368137.jpg", detailImageUrl: "https://www.bedetheque.com/media/Planches/PlancheA_387679.jpg", summary: "Le grand retour de la Première Famille de l'univers Marvel ! Lorsqu'un adversaire presque invincible se met en travers de la route de Reed Richards, ..", rating: "★★★★☆", galleryImages: ["https://www.bedetheque.com/media/Planches/PlancheA_340537.jpg"] },
    { id: 20, title: "Doctor Strange : Muste have", genre: "scifi", mediaType: "comics", price: 1200, date: "2023-07-05", minVolume: 1, maxVolume: 1, author: "Brandon Peterson", pages: 160, format: "CBR, CBZ", imageUrl: "https://www.excalibur-comics.fr/16647-large_default/docteur-strange-le-debut-de-la-fin-must-have.jpg", detailImageUrl: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1650910396-51PvVlfvH1L._SL500_.jpg?crop=1xw:1xh;center,top&resize=980:*", summary: "Le Docteur Stephen Strange est un brillant chirurgien, on ne peut plus sûr de lui, mais le destin lui réserve des surprises qu'il n'aurait jamais pu anticiper, et qui le forceront à explorer les recoins les plus secrets de son coeur... et les frontières les plus éloignées du cosmos ! Le Maître des Arts Mystiques est né !", rating: "★★★★☆", galleryImages: ["https://cdn.marvel.com/u/prod/marvel/i/mg/3/b0/6630175697ccb/clean.jpg"] },
    { id: 21, title: "Marvel Venom HS : 3e série", genre: "scifi", mediaType: "comics", price: 1000, date: "2019-10-06", minVolume: 1, maxVolume: 2, author: "Danny Cates", pages: 96, format: "CBR, CBZ", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_434377.jpg", detailImageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_405105.jpg", summary: "L'assaut du Dieu des Symbiotes sur l'univers Marvel n'impacte évidemment personne autant qu'Eddie Brock, alias Venom ! Cet album spécial regroupe tous les épisodes liés à l'événement King in Black, scénarisés par Donny Cates, l'auteur du crossover !", rating: "★★★★☆", galleryImages: ["https://www.bedetheque.com/media/Couvertures/Couv_426206.jpg"] },
    { id: 22, title: "Nightwing : Infinite", genre: "scifi", mediaType: "comics", price: 1000, date: "2022-02-25", minVolume: 1, maxVolume: 7, author: "Tom Taylor", pages: 160, format: "CBR", imageUrl: "https://bdi.dlpdomain.com/album/9791026819707/couv/I500x800/nightwing-infinite-tome-1.jpg", detailImageUrl: "https://bdi.dlpdomain.com/album/9791026826866/couv/I485x762/nightwing-infinite-tome-3.jpg", summary: "Nightwing est enfin de retour, et il a la ferme intention de reprendre son rôle de sentinelle au coeur de sa ville d'adoption, Blüdhaven. Ses concitoyens viennent cependant d'élire un nouveau maire au nom bien familier : un certain Zucco.", rating: "★★★★☆", galleryImages: [""] },
    { id: 23, title: "Joker : The Winning Card", genre: "action", mediaType: "comics", price: 1000, date: "2024-07-05", minVolume: 1, maxVolume: 1, author: "Tom King", pages: 112, format: "CBZ", imageUrl: "https://bdi.dlpdomain.com/album/9791026829126/couv/M385x862/joker-the-winning-card.jpg", detailImageUrl: "https://bdi.dlpdomain.com/album/9791026825623/couv/M385x862/joker-the-winning-card-couverture-variante-batman.jpg", summary: "Batman, Année Un. Alors que Bruce Wayne est encore en phase d'apprentissage pour incarner pleinement le Chevalier Noir, Gordon se lance sur la trace d'un mystérieux clown psychotique en pleine folie meurtrière. Ses intentions sont floues, ses mobiles inexistants, et alors que Gotham est plongée dans la peur, Gordon et Batman vont apprendre ce qu'il en coûte de sous-estimer le Joker.", rating: "★★★★☆", galleryImages: [""] },
    { id: 24, title: "Sojourn", genre: "aventure", mediaType: "comics", price: 600, date: "2004-04-08", minVolume: 1, maxVolume: 34, author: "Ron Marz", pages: 106, format: "CBZ", imageUrl: "https://www.bdfugue.com/media/catalog/product/cache/072aec3fcd47dee2d0b978892a40d848/9/7/9782848570907_1_75.jpg", detailImageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_284648.jpg", summary: "Après des années d'une guerre sans merci, les peuples des cinq terres s'unissent sous la direction d'un seul homme et défont le tyrannique Mordath. Trois cent ans plus tard, une force mystérieuse ressuscite Mordath qui reprend son impitoyable marche conquérante. La vague destructrice croise la route d'Arwyn et de sa famille. Seule survivante, elle n'a qu'un seul but : tuer Mordath.", rating: "★★★★☆", galleryImages: [""] },
    { id: 25, title: "Dark Souls", genre: "fantasy", mediaType: "comics", price: 600, date: "2016-11-30", minVolume: 1, maxVolume: 4, author: "George Mann", pages: 27, format: "CBR", imageUrl: "https://www.bdfugue.com/media/catalog/product/cache/072aec3fcd47dee2d0b978892a40d848/9/7/9791035505806_1_75.jpg", detailImageUrl: "https://www.bdfugue.com/media/catalog/product/cache/072aec3fcd47dee2d0b978892a40d848/9/7/9791035504304_1_75_1.jpg", summary: "Dans un monde où les hordes démoniaques sont légions, une guerrière qui a tout perdue se lance dans une quête vengeresse. Une aventure inédite empruntant l'univers vidéoludique de Dark Souls.", rating: "★★★★☆", galleryImages: [""] },
    { id: 26, title: "Parallel Paradise", genre: "fantasy", mediaType: "manga", price: 700, date: "2025-05-25", minVolume: 1, maxVolume: 11, author: "Seven Seas", pages: 192, format: "CBZ", imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Parallel_Paradise_volume_1_cover.jpg/250px-Parallel_Paradise_volume_1_cover.jpg", detailImageUrl: "https://m.media-amazon.com/images/I/81JYLuqOyjL._AC_UF1000,1000_QL80_.jpg", summary: "Un jour alors qu'il est en cours, Youta voit un individu à l'allure étrange rentrer dans son école.", rating: "★★★★☆", galleryImages: [""] },
    { id: 27, title: "Phantom Seer", genre: "action", mediaType: "manga", price: 800, date: "2022-09-21", minVolume: 1, maxVolume: 4, author: "Togo Goto, Kento Matsuura", pages: 192, format: "CBZ", imageUrl: "https://m.media-amazon.com/images/I/81LBLUG-gpL.jpg", detailImageUrl: "https://www.planetebd.com/dynamicImages/album/page/large/48/91/album-page-large-48914.jpg", summary: "Issu d'une lignée qui fait trembler les créatures paranormales, Iori est un puissant médium capable d'exorciser les esprits malfaisants appelés phantom. Or, ce lycéen fainéant, égoïste et désagréable ne rêve que d'une chose : une vie banale. ", rating: "★★★★☆", galleryImages: [""] },
    { id: 28, title: "Blame", genre: "mystere", mediaType: "manga", price: 600, date: "1998", minVolume: 1, maxVolume: 10, author: "Tsutomu MIHEI", pages: 182, format: "CBZ", imageUrl: "https://www.manga-news.com/public/images/series/blame-de-luxe-1-glenat.webp", detailImageUrl: "https://www.planetebd.com/dynamicImages/album/cover/large/38/43/album-cover-large-38438.jpg", summary: "Le monde est régi par une cyber-entité omnisciente, qui pourrait être un dérivé du net. L'héroïne, Musubi Susono, est une inspectrice qui enquête sur une mystérieuse affaire de disparitions d'enfants, en compagnie de son collègue Clauthor.", rating: "★★★★☆", galleryImages: [""] },
    { id: 29, title: "Doubt", genre: "mystere", mediaType: "manga", price: 700, date: "2007", minVolume: 1, maxVolume: 4, author: "Tonogai", pages: 200, format: "CBR", imageUrl: "https://www.bdfugue.com/media/catalog/product/cache/1f6f2b21905e2338a7ddd5f5557a2426/9/7/9782355923326_1_75.jpg", detailImageUrl: "https://12dimension.wordpress.com/wp-content/uploads/2011/06/doubt109.jpg", summary: "Rabbit Doubt fait fureur au Japon : dans ce jeu sur téléphone portable, des lapins doivent débusquer le loup qui se cache parmi eux. Quant au loup, il doit utiliser tous les subterfuges possibles pour semer la confusion dans le groupe et éliminer un par un tous ses adversaires.Mais pour cinq fans du jeu, Rabbit Doubt ne tarde pas à virer au cauchemar : ils se réveillent enfermés dans un bâtiment désaffecté avec, à leurs côtés, le corps d'une camarade assassinée.", rating: "★★★★☆", galleryImages: [""] },
    { id: 30, title: "Yahari Ore no Seishun Love Come wa Machigatteiru", genre: "fantasy", mediaType: "manga", price: 500, date: "2012", minVolume: 1, maxVolume: 17, author: "Wataru WATARI", pages: 186, format: "CBR", imageUrl: "https://www.manga-news.com/public/images/vols/my-teen-romantic-comedy-4-ototo.jpg", detailImageUrl: "https://www.nautiljon.com/images/light_novels/00/63/yahari_ore_no_seishun_love_comedy_wa_machigatteiru_shin_2536.webp", summary: "Le jeune Hachiman a une vision des plus pessimistes de la vie. De toute façon, sa situation actuelle ne le pousse guère à déborder d’optimisme : pas d’amis, pas de petite amie et sa capacité à envisager l’avenir est totalement nulle. Pour le faire changer, sa conseillère d’orientation le pousse à rejoindre le « Club des Volontaires » qui vise à aider les lycéens à résoudre leurs problèmes et à réaliser leurs rêves.", rating: "★★★★☆", galleryImages: [""] },
    { id: 31, title: "Redo Of Healer", genre: "fantasy", mediaType: "manga", price: 700, date: "2021", minVolume: 1, maxVolume: 12, author: "Tsukiyo Rui", pages: 147, format: "CBR", imageUrl: "https://m.media-amazon.com/images/M/MV5BYzYzMDM3NGYtZTIwZS00N2UxLWExYzItYmQ1ZTRiOWNjMmYzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", detailImageUrl: "https://static.wikia.nocookie.net/kaifuku/images/4/45/Light_Novel_10_Cover.jpeg/revision/latest?cb=20241123121742", summary: "Keare est un jeune paysan propulsé héros guérisseur suite à l'apparition d'une marque sur sa main. Malheureusement pour lui le voilà exploité horriblement par ses compagnons héros et par le royaume ; drogué, humilié, et violé constamment, Keare est un être brisé ne souhaitant que la vengeance.", rating: "★★★★☆", galleryImages: [""] },
    { id: 32, title: "Starving Anonymous", genre: "mystere", mediaType: "manga", price: 800, date: "2019-06-19", minVolume: 1, maxVolume: 7, author: "Yu Kuraishi", pages: 192, format: "CBR", imageUrl: "https://www.bdfugue.com/media/catalog/product/cache/0d950bd4d3aaddc02a824ea154d9c41e/9/7/9782811652005_1_75.jpg", detailImageUrl: "https://m.media-amazon.com/images/I/81kpmdV8u8L._AC_UF894,1000_QL80_.jpg", summary: "En plein mois de mars, le Japon est frappé par une exceptionnelle et inexplicable vague de chaleur. Iyé, lycéen qui aimerait devenir dessinateur, est soudainement kidnappé alors qu’il rentre de l’école avec son ami Kazu. Il se réveille dans un hangar, entouré d’hommes congelés et d’autres totalement hagards et obèses. Le paysage qui s’offre à lui est terrifiant, mais il est loin d’être au bout de ses surprises.", rating: "★★★★☆", galleryImages: [""] },
    { id: 33, title: "Ayashimon", genre: "aventure", mediaType: "manga", price: 600, date: "2021", minVolume: 1, maxVolume: 3, author: "Yuji KAKU", pages: 192, format: "CBZ", imageUrl: "https://www.manga-news.com/public/images/vols/Ayashimon_T01_-_Crunchyroll.jpg", detailImageUrl: "https://img.sanctuary.fr/fiche/origin/70393.jpg", summary: "Maruo est un adolescent dont la passion pour les mangas n’a d’égale que la force physique. Cette puissance, qui ne lui a jusque-là attiré qu'une cascades d'ennuis, l'amène à sauver par hasard la jeune Urara, fille cachée d'un chef yakuza décédé dans d'étranges circonstances. En devenant son garde du corps, Maruo est en passe de réaliser son rêve : se battre contre de vigoureux adversaires à l'image de ses icônes, les héros de shônen ! De son côté, Urara, en quête de vengeance, va dévoiler à Maruo les arcanes d'un monde inconnu des humains, celui des ayashimon, autrement dit, des démons-yakuzas…", rating: "★★★★☆", galleryImages: [""] },
    { id: 34, title: "Owari No Seraph", genre: "aventure", mediaType: "manga", price: 600, date: "2013", minVolume: 1, maxVolume: 29, author: "Yamato YAMAMOTO", pages: 190, format: "CBZ", imageUrl: "https://www.manga-news.com/public/images/series/.seraph-of-the-end-1-kana_large.webp", detailImageUrl: "https://cdn.verasia.fr/27696-thickbox_default_2x/seraph-of-the-end-vol-29-owari-no-seraph.jpg", summary: "Alors qu’un virus a décimé une partie de l’humanité, les vampires ont pris le pouvoir ! ls élèvent les enfants comme du bétail pour se repaître de leur sang. Ils n’hésitent pas à les tuer. Afin de venger la mort de ses amis, Yûichiro s’enrôle dans un bataillon d’extermination de vampires. Il sera aidé par l’intrépide Shinoa et par son arme possédée par un démon mais qui se dressera devant lui ?!", rating: "★★★★☆", galleryImages: [""] },
    { id: 35, title: "Gotoubun No Hanayome", genre: "fantasy", mediaType: "manga", price: 600, date: "2017", minVolume: 1, maxVolume: 14, author: "Negi HARUBA", pages: 200, format: "PDF", imageUrl: "https://www.manga-news.com/public/images/series/.The-quintescence-quintuplets-1-pika_large.webp", detailImageUrl: "https://cdn.verasia.fr/19676/go-tobun-no-hanayome-the-quintessential-quintuplets-vol-14-full-color-edition.jpg", summary: "Fûtarô, un lycéen brillant mais fauché, décroche un petit boulot de rêve : professeur particulier pour une famille fortunée. Or, le garçon déchante lorsqu’il réalise que ce n’est pas un élève qu’il va devoir gérer, mais des quintuplées aussi belles que cancres à souhait… Entre Ichika la désordonnée, Nino la protectrice, Miku la réservée, Yotsuba la joviale et Itsuki la susceptible, Fûtarô va devoir prendre son courage à deux mains pour relever le défi que représentent les sœurs Nakano!", rating: "★★★★☆", galleryImages: [""] },
    { id: 36, title: "Marchen Crown", genre: "fantasy", mediaType: "manga", price: 400, date: "2025", minVolume: 1, maxVolume: 17, author: "Azychika", pages: 20, format: "CBZ", imageUrl: "https://jumpg-assets.tokyo-cdn.com/secure/title/100468/title_thumbnail_portrait_list/407370.jpg?hash=p19D8IXlLagFc_KZnhAL6Q&expires=2145884400", detailImageUrl: "https://www.manga-news.com/public/images/series/Marchen-Crown-1-jp.webp", summary: "Raiponce est une jeune fille qui vit au sommet d'une haute tour et ignore tout du monde extérieur. Un jour, elle rencontre un garçon nommé Mikel, qui escalade la tour, et leur destin, qui les mènera à changer le monde, commence à se dessiner ! Les créateurs d'« Oshi no Ko » et de « Record of Ragnarok » forment une équipe incroyable pour vous offrir une histoire d'amour extraordinaire !", rating: "★★★★☆", galleryImages: [""] },
    { id: 37, title: "Embers", genre: "aventure", mediaType: "manga", price: 500, date: "2025", minVolume: 1, maxVolume: 14, author: "Karumazaki Kei", pages: 192, format: "CBR", imageUrl: "https://www.nautiljon.com/images/manga_volumes/12/62/embers_11020026.webp?1752751034", detailImageUrl: "https://dwgkfo5b3odmw.cloudfront.net/manga/thumbs/new/chapter/Embers2/_web-qFHD_zX5QfTpfK1Vn6PhWA.jpg", summary: "Noboru Haitani, un collégien, passe son temps à se battre. Lui qui ne perd jamais un combat, il subit un jour une cuisante défaite lors d'un duel au football. Par frustration, Haitani se passionne de plus en plus pour ce sport, jusqu'au jour où il est contraint de jouer un match contre l'équipe de Takami, le prodige du collège ! Un hors-la-loi fait son entrée dans le monde du football !", rating: "★★★★☆", galleryImages: [""] },
    { id: 38, title: "Momo : The Blood Taker", genre: "mystere", mediaType: "manga", price: 400, date: "2019", minVolume: 1, maxVolume: 45, author: "Sugito Akira", pages: 35, format: "CBR", imageUrl: "https://www.nautiljon.com/images/manga/00/66/momo_-_the_blood_taker_10466.webp", detailImageUrl: "https://images.penguinrandomhouse.com/cover/9798888436608", summary: "À Tokyo, de mystérieux cas se produisent où les victimes sont retrouvées vidées de tout leur sang.L'histoire nous entraîne aux côtés de Keiji Mikogami, un détective cherchant le coupable du meurtre atroce de sa femme, connu sous le nom de l'homme aux deux visages.Dans l'ombre, un jeune fille aux cheveux argentés l'observe. Quelle est l'identité de cette mystérieuse personne ?", rating: "★★★★☆", galleryImages: [""] },
    { id: 39, title: "I Love You So I Kill You", genre: "mystere", mediaType: "manga", price: 500, date: "2015", minVolume: 1, maxVolume: 10, author: "Soso Sakakibara", pages: 180, format: "CBR", imageUrl: "https://www.manga-news.com/public/images/series/i-Love-You-So-kill-you-1-soleil.webp", detailImageUrl: "https://www.manga-news.com/public/images/vols/i-love-you-so-i-kill-you-5-soleil.jpg", summary: "Kamishiro Taku aime prendre soin des plantes du lycée et son amie Mika aime le taquine sur le sujet. Elle ignore tout des sentiments de son ami. Mais sa vie bascule le jour où il tente d’intervenir lors d’une agression dans la rue. Un curieux virus va ainsi le contaminer. Dès lors, de terribles envies de meurtre l’envahissent en présence de Mika. Chaque moment passé à ses côtés est l’objet de visions de meurtres d’une rare cruauté. Pourtant, il va devoir affronter ses instincts et trouver un remède au plus vite !!!", rating: "★★★★☆", galleryImages: [""] },
    { id: 40, title: "Terra Formars", genre: "scifi", mediaType: "manga", price: 600, date: "2017", minVolume: 1, maxVolume: 22, author: "Yu Sasuga", pages: 224, format: "CBZ", imageUrl: "https://www.planetebd.com/dynamicImages/album/cover/large/19/07/album-cover-large-19075.jpg", detailImageUrl: "https://www.planetebd.com/dynamicImages/album/page/large/19/07/album-page-large-19075.jpg", summary: "An 2599. La terraformation de Mars est presque achevée. Sa surface est désormais recouverte de lichens et une forme de vie organique y prolifère. Quinze jeunes gens tout spécialement sélectionnés et préparés s'envolent à bord du vaisseau spatial Bugs 2, investis d'une mission cruciale. Ils ne se doutent pas encore que sur place, un parasite bien connu les attend de pied ferme...", rating: "★★★★☆", galleryImages: [""] },
    { id: 41, title: "Terminator 2 : Infinity", genre: "scifi", mediaType: "comics", price: 700, date: "1991", minVolume: 1, maxVolume: 5, author: "", pages: 48, format: "CBR, CBZ", imageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_244332.jpg", detailImageUrl: "https://i5.walmartimages.com/seo/Terminator-2-Infinity-1A-VF-Dynamite-Comic-Book_fcda4358-9076-4eff-bd19-59c825b41706.e037b107d68c63b76252d8901e987e90.jpeg", summary: "Nous sommes en 2033. La dernière installation de surface de Skynet a été prise d'assaut par la Résistance . Le cœur de Skynet est intact. Skynet constate un déséquilibre dans la ligne temporelle principale. En simulant des lignes temporelles alternatives, elle découvre plusieurs voies à l'origine de cette anomalie. Une quatrième voie est identifiée : il s'agit de la cause principale du déséquilibre. Skynet lance alors le voyage temporel du prototype T-Infinity pour corriger cette voie.", rating: "★★★★☆", galleryImages: [""] },
    { id: 42, title: "Avengers : Infiity War", genre: "action", mediaType: "comics", price: 900, date: "2019", minVolume: 1, maxVolume: 7, author: "", pages: 117, format: "CBZ, CBR", imageUrl: "https://www.planetebd.com/dynamicImages/album/cover/large/44/15/album-cover-large-44150.jpg", detailImageUrl: "https://www.bedetheque.com/media/Couvertures/Couv_372660.jpg", summary: "Les super-héros détiennent les Gemmes de l’Infini mais un personnage nommé Requiem tente de s’en emparer. Le nouvel event Marvel séduit par un visuel de toute beauté mais nous perd dans des limbes étranges et infinies.", rating: "★★★★☆", galleryImages: [""] },

];

const PRICE_MAP = ALL_PRODUCTS.map(p => ({
    id: p.id,
    title: p.title,
    price: p.price
}));
